version: 2
jobs:
  test:
    working_directory: ~/micro-cors-multiple-allow-origin
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - restore_cache:
          name: Restoring Cache - dependencies
          keys:
            - v1-dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: System information
          command: |
            echo "Node.js $(node -v)"
            echo "npm $(npm -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: ESLint
          command: yarn run lint
      - run:
          name: Test
          command: yarn test
      - save_cache:
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
          key: v1-dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}

workflows:
  version: 2
  test:
    jobs:
      - test
